### ISSUE TITLE
npm version not remove console.logs

### ISSUE THREAD

**Issue by kefengwei** [Fileless/ng-oidc-client#7]
npm version: 1.0.4
No matter what log level configured, once you logged the console always print logs. Then the browser will dead!

**Comment by alx-andru** [comment]
@kefengwei Can you test 1.0.5 and see if the removing of the log messages helped in your case?

**Comment by kefengwei** [comment]
@alx-andru  There is no log messages in 1.0.5. Thank for your update.

**Comment by alx-andru** [comment]
Hey @kefengwei thank you very much for confirming. Closing the issue then
